name: Build and deploy

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:22
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: node_modules
        key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-${{ runner.os }}-
    - run: yarn install --fronzen-lockfile
    - run: yarn build
    - uses: actions/upload-pages-artifact@v3
      with:
        path: dist/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/deploy-pages@v4
      id: deployment
