name: Lint

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:22
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: node_modules
        key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-${{ runner.os }}-
    - run: yarn install --fronzen-lockfile
    - run: |
        yarn prettier:check
        yarn lint
